import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Vestir Backend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Vestir Backend</h1>
        <h2>Routes</h2>
        <ul>
          <li>
            <ul>
              Products
              <li>/api/products - get all products</li>
              <li>/api/products/:productId - get individual product</li>
            </ul>
          </li>
          <li>
            <ul>
              Auth
              <li>/api/auth/login</li>
              <li>/api/auth/signup</li>
              <li>
                /api/auth/generate-token - get new token from refresh token
              </li>
            </ul>
          </li>
          <li>
            <ul>
              Categories
              <li>/api/categories - get all categories</li>
              <li>/api/categories/:categoryId - get category</li>
            </ul>
          </li>
        </ul>
      </main>
    </>
  );
}
